#/bin/bash

# build directory structure
if [ ! -d INPUT ] ; then mkdir INPUT ; fi
if [ ! -d RESTART ] ; then mkdir RESTART ; fi

# get input files
if [ ! -f INPUT/coordinates_NPAC_profile.nc ] ; then ln -s ../../docs/coordinates_NPAC_profile.nc ./INPUT/. ; fi
if [ ! -f INPUT/h2_wide_chan.nc ] ; then ln -s ../../docs/h2_wide_chan.nc ./INPUT/. ; fi

# get executable
if [ ! -f MOM6 ] ; then ln -s ../build/MOM6 . ; fi

# source env
. ../scripts/gaea-intel-env

# run model
srun -n 2 ./MOM6
